name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies (Stream Processor)
      run: |
        python -m pip install --upgrade pip
        pip install -r stream_processor/requirements.txt
        
    - name: Run Tests (Stream Processor)
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/stream_processor
        pytest stream_processor/tests/
        
    - name: Install dependencies (API Service)
      run: |
        pip install -r api_service/requirements.txt
        
    - name: Run Tests (API Service)
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/api_service
        pytest api_service/tests/

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Producer Simulator
      run: docker build -t producer_simulator ./producer_simulator
      
    - name: Build Stream Processor
      run: docker build -t stream_processor ./stream_processor
      
    - name: Build API Service
      run: docker build -t api_service ./api_service
